version: '2'
services:
  web:
    build: .
    command: npm -v
    volumes:
      - .:/work
    ports:
      - "3001:3000"
#    depends_on:
#      - bundle
#  bundle:
#    image: standarduieditorce_web
#    command: npm run bundle-example
#    ports:
#      - "3123:3123"
#    volumes:
#      - .:/work
